### ISSUE TITLE
Does not report unfollowers

### ISSUE THREAD

**Issue by vekvoid** [davidesantangelo/tuns#2]
Hi,

Tuns has just stopped working for me. I tried with multiple accounts but just doesn't show the unfollowers. I tried deleting the Tuns account and revoking the access from twitter, but still not working.

The last Tuns email notification I received was on March 25th.
If you need more information, I will try to give it.

Regards.

**Comment by davidesantangelo** [comment]
I just restored service at https://www.tunsapp.com. But without email, just only dashboard for Now.
